# Generated by Django 4.2.1 on 2023-06-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentroDeEstudios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="centro de estudios"),
                ),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "apellido1",
                    models.CharField(max_length=50, verbose_name="primer apellido"),
                ),
                (
                    "apellido2",
                    models.CharField(max_length=50, verbose_name="segundo apellido"),
                ),
                ("f_nac", models.DateField(verbose_name="fecha de nacimiento")),
            ],
        ),
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="centro_de_estudios.persona",
                    ),
                ),
            ],
            bases=("centro_de_estudios.persona",),
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="centro_de_estudios.persona",
                    ),
                ),
                ("dni", models.CharField(max_length=9, verbose_name="DNI")),
            ],
            bases=("centro_de_estudios.persona",),
        ),
        migrations.CreateModel(
            name="MatriculaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="matrícula"
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(auto_now_add=True, verbose_name="fecha de alta"),
                ),
                ("fecha_baja", models.DateField(verbose_name="fecha de baja")),
                (
                    "centroDeEstudios",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centro_de_estudios.centrodeestudios",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centro_de_estudios.alumno",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="centrodeestudios",
            name="alumnos",
            field=models.ManyToManyField(
                through="centro_de_estudios.MatriculaAlumno",
                to="centro_de_estudios.alumno",
            ),
        ),
    ]
