# Generated by Django 4.2.1 on 2023-06-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "centro_de_estudios",
            "0002_profesorempleado_estudio_curso_asignatura_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f_inicio",
                    models.DateField(auto_now_add=True, verbose_name="fecha de inicio"),
                ),
                ("f_fin", models.DateField(verbose_name="fecha de fin")),
                ("seccion", models.CharField(max_length=10, verbose_name="sección")),
                ("descripcion", models.TextField(verbose_name="descripción")),
                ("alumnos", models.ManyToManyField(to="centro_de_estudios.alumno")),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centro_de_estudios.asignatura",
                    ),
                ),
                (
                    "curso_grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centro_de_estudios.curso",
                    ),
                ),
                (
                    "profesores",
                    models.ManyToManyField(to="centro_de_estudios.profesor"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alumno",
            name="grupos",
            field=models.ManyToManyField(to="centro_de_estudios.grupo"),
        ),
        migrations.AddField(
            model_name="curso",
            name="grupos",
            field=models.ManyToManyField(to="centro_de_estudios.grupo"),
        ),
    ]
