# Generated by Django 4.2.1 on 2023-06-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centro_de_estudios", "0004_alumno_id_alumno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="id_alumno",
            field=models.CharField(
                default="0000000000", max_length=10, verbose_name="id"
            ),
        ),
    ]
