# Generated by Django 4.2.1 on 2023-06-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("centro_de_estudios", "0005_alter_alumno_id_alumno"),
        ("centro_de_estudios", "0006_alter_persona_f_nac"),
    ]

    operations = []
