# Generated by Django 4.2.1 on 2023-06-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "modelos_de_alumnos",
            "0004_rename_caracteristica_valorseleccion_caracteristica",
        ),
        ("centro_de_estudios", "0007_merge_20230608_1911"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, null=True, verbose_name="nombre"),
                ),
                ("alumnos", models.ManyToManyField(to="centro_de_estudios.alumno")),
            ],
        ),
        migrations.CreateModel(
            name="Agrupamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        max_length=200, null=True, verbose_name="etiqueta"
                    ),
                ),
                (
                    "equipos",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trabajo_colaborativo.equipo",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelos_de_alumnos.definicionmodelo",
                    ),
                ),
            ],
        ),
    ]
