# Generated by Django 4.2.1 on 2023-06-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trabajo_colaborativo",
            "0002_equipo_id_agrupamiento_remove_agrupamiento_equipos_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipo",
            old_name="id_agrupamiento",
            new_name="de_agrupamiento",
        ),
    ]
