# Generated by Django 4.2.1 on 2023-06-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos_de_alumnos", "0005_definicionmodelo_descripcion"),
        ("trabajo_colaborativo", "0003_rename_id_agrupamiento_equipo_de_agrupamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="agrupamiento",
            name="caracteristicas",
            field=models.ManyToManyField(
                blank=True, to="modelos_de_alumnos.caracteristica"
            ),
        ),
        migrations.AddField(
            model_name="agrupamiento",
            name="tipo",
            field=models.CharField(max_length=20, null=True, verbose_name="tipo"),
        ),
    ]
