# Generated by Django 4.2.1 on 2023-06-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos_de_alumnos", "0002_alter_caracteristica_etiqueta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datomodelo",
            name="id_alumno",
            field=models.CharField(max_length=10, verbose_name="id_alumno"),
        ),
    ]
